import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";
import { type Inventory, routeKey } from "./inventory.js";
import { runSpecSync, type Finding } from "./spec-sync.js";

export const GENERATED_DOC_FILES = ["api.md", "behaviors.md", "gauntlet.md", "gaps.md"] as const;

const HEADER = `<!--
  Generated by scripts/generate-docs.ts. Do not edit by hand.
  Source of truth: features/, openapi/, gauntlet.config.json, src/
-->`;

function mdTable(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((row) => `| ${row.join(" | ")} |`);
  return [head, sep, ...body].join("\n");
}

function cell(value: string): string {
  return value.replace(/\|/g, "\\|") || "—";
}

function renderApi(inventory: Inventory): string {
  const opRows = inventory.operations.map((op) => {
    const tagged = inventory.scenarios
      .filter((scenario) => op.operationId && scenario.operationIds.includes(op.operationId))
      .map((scenario) => scenario.name);
    return [
      cell(op.operationId ?? "(missing)"),
      op.method.toUpperCase(),
      cell(op.path),
      cell(tagged.join("; ") || "(none)"),
    ];
  });
  const routeRows = inventory.routes.map((route) => {
    const inOpenApi = inventory.operations.some(
      (op) =>
        routeKey(op.method, op.normalizedPath) === routeKey(route.method, route.normalizedPath),
    );
    const listed = (inventory.config.allowlist ?? []).find(
      (entry) => routeKey(entry.method, entry.path) === routeKey(route.method, route.path),
    );
    return [
      route.method.toUpperCase(),
      cell(route.path),
      inOpenApi ? "yes" : "no",
      cell(listed ? listed.kind : ""),
    ];
  });

  return `${HEADER}

# HTTP API (generated)

## OpenAPI operations

${
    opRows.length > 0
      ? mdTable(["operationId", "method", "path", "@op scenario"], opRows)
      : "_No OpenAPI operations._"
  }

## Implemented routes

${
    routeRows.length > 0
      ? mdTable(["method", "path", "in OpenAPI", "allowlist"], routeRows)
      : "_No routes discovered._"
  }
`;
}

function renderBehaviors(inventory: Inventory): string {
  const byFile = new Map<string, typeof inventory.scenarios>();
  for (const scenario of inventory.scenarios) {
    const list = byFile.get(scenario.featureFile) ?? [];
    list.push(scenario);
    byFile.set(scenario.featureFile, list);
  }
  const sections: string[] = [];
  for (const file of [...byFile.keys()].sort((a, b) => a.localeCompare(b))) {
    const scenarios = byFile.get(file) ?? [];
    const items = scenarios.map((scenario) => {
      const tags =
        scenario.tags.length > 0
          ? scenario.tags.map((tag) => "`" + tag + "`").join(" ")
          : "_none_";
      return `- **${scenario.name}** — tags: ${tags}`;
    });
    sections.push(`## ${file}\n\n${items.join("\n")}`);
  }

  return `${HEADER}

# Behaviors (generated)

Gherkin is the behavior surface. Link HTTP operations with \`@op:<operationId>\`.

${sections.length > 0 ? sections.join("\n\n") : "_No scenarios found._"}
`;
}

function renderGauntlet(inventory: Inventory): string {
  const gates = inventory.config.gates.map((gate, index) => {
    const enabled = gate.enabled === false ? "skipped" : "enabled";
    return `${index + 1}. \`${gate.id}\` (${enabled}) — \`${gate.command} ${gate.args.join(" ")}\``;
  });
  const allowRows = (inventory.config.allowlist ?? []).map((entry) => [
    entry.method.toUpperCase(),
    cell(entry.path),
    entry.kind,
    cell(entry.exemptFrom.join(", ")),
    cell(entry.owner),
    entry.expires,
  ]);

  return `${HEADER}

# Gauntlet (generated)

- **App:** ${inventory.config.name ?? "(unnamed)"}
- **Strictness:** ${inventory.strictness}

## Gates

${gates.length > 0 ? gates.join("\n") : "_No gates configured._"}

## Allowlist

${
    allowRows.length > 0
      ? mdTable(["method", "path", "kind", "exemptFrom", "owner", "expires"], allowRows)
      : "_No allowlist entries._"
  }

## Policy

- Surfaces: features (behavior), OpenAPI (HTTP), unit ↔ domain (HOW)
- Link operations to scenarios with \`@op:<operationId>\`
- Allowlist kinds: \`test-harness\` | \`static-ui\` | \`internal\` | \`wip-red\`
- Required allowlist fields: kind, method, path, reason, exemptFrom, owner, expires
- Seed allowlist entries expire **2026-12-02**; renew before that date (expired entries do not exempt)
- protect-specs and no-cheat are hard tools, not polite requests
`;
}

function renderGaps(findings: Finding[]): string {
  const durable = findings.filter((finding) => finding.id !== "D6" && finding.id !== "D9");
  const blocking = durable.filter((finding) => finding.severity === "fail");
  const warnings = durable.filter((finding) => finding.severity === "warn");
  const notes = durable.filter((finding) => finding.severity === "info");

  const list = (items: Finding[]): string =>
    items.length > 0
      ? items.map((item) => `- **${item.id}:** ${item.message}`).join("\n")
      : "_None._";

  return `${HEADER}

# Spec-sync gaps (generated)

Live D6 (git differential) and D9 (no-cheat) appear in \`gauntlet-report.json\` / CI logs, not in this committed file.

## Blocking

${list(blocking)}

## Warnings

${list(warnings)}

## Notes

${list(notes)}

D6 (git differential) and D9 (no-cheat coverage baseline) are evaluated at
verify time and are not snapshotted here, so D7 stays deterministic.
`;
}

export function renderGeneratedDocs(
  inventory: Inventory,
  findings: Finding[],
): Record<string, string> {
  return {
    "api.md": renderApi(inventory).trimEnd() + "\n",
    "behaviors.md": renderBehaviors(inventory).trimEnd() + "\n",
    "gauntlet.md": renderGauntlet(inventory).trimEnd() + "\n",
    "gaps.md": renderGaps(findings).trimEnd() + "\n",
  };
}

export function writeGeneratedDocs(docs: Record<string, string>, outDir: string): string[] {
  mkdirSync(outDir, { recursive: true });
  const written: string[] = [];
  for (const name of GENERATED_DOC_FILES) {
    const path = join(outDir, name);
    writeFileSync(path, docs[name] ?? "");
    written.push(path);
  }
  return written;
}

export function generateDocs(
  cwd = process.cwd(),
  outDir = resolve(cwd, "docs/generated"),
): string[] {
  const result = runSpecSync(cwd);
  const docs = renderGeneratedDocs(result.inventory, result.findings);
  const written = writeGeneratedDocs(docs, outDir);
  console.info(`generated ${written.length} docs under ${outDir}`);
  return written;
}

function isDirectRun(): boolean {
  const entry = process.argv[1];
  if (!entry) {
    return false;
  }
  return fileURLToPath(import.meta.url) === resolve(entry);
}

if (isDirectRun()) {
  generateDocs();
}
